openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/members/:
    get:
      operationId: listMembers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Member'
          description: ''
      tags:
      - api
    post:
      operationId: createMember
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Member'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Member'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
          description: ''
      tags:
      - api
  /api/members/{id}/:
    get:
      operationId: retrieveMember
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this member.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
          description: ''
      tags:
      - api
    put:
      operationId: updateMember
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this member.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Member'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Member'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateMember
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this member.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Member'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Member'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyMember
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this member.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/venues/:
    get:
      operationId: listVenues
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Venue'
          description: ''
      tags:
      - api
    post:
      operationId: createVenue
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Venue'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Venue'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Venue'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
          description: ''
      tags:
      - api
  /api/venues/{id}/:
    get:
      operationId: retrieveVenue
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this venue.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
          description: ''
      tags:
      - api
    put:
      operationId: updateVenue
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this venue.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Venue'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Venue'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Venue'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateVenue
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this venue.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Venue'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Venue'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Venue'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyVenue
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this venue.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/devices/:
    get:
      operationId: listDevices
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
          description: ''
      tags:
      - api
    post:
      operationId: createDevice
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Device'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
          description: ''
      tags:
      - api
  /api/devices/{id}/:
    get:
      operationId: retrieveDevice
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this device.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
          description: ''
      tags:
      - api
    put:
      operationId: updateDevice
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this device.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Device'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateDevice
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this device.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Device'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyDevice
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this device.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/users/:
    get:
      operationId: listUsers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
    post:
      operationId: createUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
  /api/users/{id}/:
    get:
      operationId: retrieveUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
    put:
      operationId: updateUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyUser
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this user.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Member:
      type: object
      properties:
        hku_id:
          type: string
          maxLength: 10
        name:
          type: string
          maxLength: 150
        is_close_contact:
          type: boolean
      required:
      - hku_id
      - name
      - is_close_contact
    Venue:
      type: object
      properties:
        venue_code:
          type: string
          maxLength: 20
        location:
          type: string
          maxLength: 150
        venue_type:
          type: string
          maxLength: 2
        capacity:
          type: integer
        is_poorly_ventilated_area:
          type: boolean
      required:
      - venue_code
      - location
      - venue_type
      - capacity
      - is_poorly_ventilated_area
    Device:
      type: object
      properties:
        hku_id:
          type: string
          maxLength: 10
        venue_code:
          type: string
          maxLength: 150
        time_of_record:
          type: string
          format: date-time
        is_an_entry_record:
          type: boolean
      required:
      - hku_id
      - venue_code
      - time_of_record
      - is_an_entry_record
    User:
      type: object
      properties:
        username:
          type: string
          maxLength: 50
        password:
          type: string
          maxLength: 50
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        email:
          type: string
          maxLength: 100
        is_admin:
          type: boolean
      required:
      - username
      - password
      - first_name
      - last_name
      - email
      - is_admin
